services:
  mongodb:
    image: mongo:7
    ports: ['27017:27017']
    environment:
      MONGO_INITDB_DATABASE: forms
    volumes: [mongo_data:/data/db]
  mongo-express:
    image: mongo-express:1
    ports: ['8081:8081']
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH: 'false'
    depends_on: [mongodb]
volumes:
  mongo_data:
